import {
    //NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { PiFolder, PiHouse, PiFile, PiKanban, PiNotebook, PiWrench, PiUsers, PiChat, PiFileText, PiGear, PiDresser, PiAlignBottom } from 'react-icons/pi'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: PiHouse,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'PIESAR', 'MAGAZIE', 'VANZATOR', 'OPERATOR', 'RECEPTION'],
        subMenu: [],
    },
    {
        key: 'reports',
        path: '/reports',
        title: 'Reports',
        translateKey: 'Reports',
        icon: PiAlignBottom,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN'],
        subMenu: [],
    },
    /** Example purpose only, please remove */
    {
        key: 'proiecte',
        path: '/proiecte',
        title: 'Projects',
        translateKey: 'Projects',
        icon: PiFolder,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'PIESAR', 'MAGAZIE', 'VANZATOR', 'OPERATOR', 'RECEPTION'],
        subMenu: [],
    },

    {
        key: 'documente',
        path: '/documente',
        title: 'Documents',
        translateKey: 'Documents',
        icon: PiFile,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'VANZATOR', 'RECEPTION'],
        subMenu: [],
    },
    {
        key: 'sarcini',
        path: '/sarcini',
        title: 'Tasks',
        translateKey: 'Tasks',
        icon: PiKanban,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'VANZATOR', 'OPERATOR'],
        subMenu: [],
    },
    {
        key: 'constatari',
        path: '/constatari',
        title: 'Statements',
        translateKey: 'Statements',
        icon: PiNotebook,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'RECEPTION', 'OPERATOR', 'VANZATOR'],
        subMenu: [],
    },
    {
        key: 'piese',
        path: '/piese',
        title: 'Parts',
        translateKey: 'Parts',
        icon: PiWrench,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'PIESAR', 'MAGAZIE'],
        subMenu: [],
    },
    {
        key: 'magazie',
        path: '/magazie',
        title: 'Storage',
        translateKey: 'Storage',
        icon: PiDresser,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'PIESAR', 'MAGAZIE'],
        subMenu: [],
    },
    {
        key: 'clienti',
        path: '/clienti',
        title: 'Clients',
        translateKey: 'Clients',
        icon: PiUsers,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'VANZATOR', 'RECEPTION'],
        subMenu: [],
    },
    {
        key: 'chat',
        path: '/chat/ChatPage',
        title: 'Chat',
        translateKey: 'Chat',
        icon: PiChat,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'PIESAR', 'MAGAZIE', 'VANZATOR', 'OPERATOR', 'RECEPTION'],
        subMenu: [],
    },
    {
        key: 'setariPlatforma',
        path: '/setari-platforma',
        title: 'Platform Settings',
        translateKey: 'Platform Settings',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'utilizatori.item1',
                path: '/utilizatori',
                title: 'Users',
                translateKey: 'Users',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['SUPER_ADMIN', 'ADMIN'],
                subMenu: [],
            },
            {
                key: 'tip-proiecte.item2',
                path: '/tip-proiecte',
                title: 'Project Types',
                translateKey: 'Project Types',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['SUPER_ADMIN', 'ADMIN'],
                subMenu: [],
            },
            {
                key: 'tip-manopera.item2',
                path: '/tip-manopera',
                title: 'Statement Types',
                translateKey: 'Statement Types',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['SUPER_ADMIN', 'ADMIN'],
                subMenu: [],
            },
            {
                key: 'sabloane-documente.item3',
                path: '/sabloane/documente',
                title: 'Document Templates',
                translateKey: 'Document Templates',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['SUPER_ADMIN', 'ADMIN', 'RECEPTION'],
                subMenu: [],
            },
            {
                key: 'sabloane-sarcini.item4',
                path: '/sabloane/sarcini',
                title: 'Task Templates',
                translateKey: 'Task Templates',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['SUPER_ADMIN', 'ADMIN'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'logs.item4',
        path: '/logs',
        title: 'Logs',
        translateKey: 'Logs',
        icon: PiFileText,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN'],
        subMenu: [],
    },
    {
        key: 'setari-cont.item5',
        path: '/setari-cont',
        title: 'Account Settings',
        translateKey: 'Account Settings',
        icon: PiGear,
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['SUPER_ADMIN', 'ADMIN', 'PIESAR', 'MAGAZIE', 'VANZATOR', 'OPERATOR', 'RECEPTION'],
        subMenu: [],
    },
]

export default navigationConfig
